import { colors } from "@/src/styles/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.gray80,
  },
  container: {
    flex: 1,
    backgroundColor: colors.gray80,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 160,
    gap: 32,
  },
  header: {
    gap: 24,
  },
  headerTitle: {
    fontSize: 26,
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.gray90,
    backgroundColor: colors.withe100,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  statIcon: {
    width: 48,
    height: 48,
    resizeMode: "contain",
  },
  statTexts: {
    flex: 1,
  },
  statValue: {
    fontSize: 22,
  },
  statLabel: {
    fontSize: 12,
    color: colors.gray100,
  },
  section: {
    gap: 16,
  },
  sectionTitle: {
    fontSize: 20,
  },
  journeyCarousel: {
    position: "relative",
    paddingVertical: 6,
  },
  journeyList: {
    paddingRight: 40,
    gap: 12,
  },
  journeyCard: {
    width: 168,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.gray90,
    backgroundColor: colors.withe100,
    gap: 18,
    position: "relative",
  },
  journeyIcon: {
    width: 58,
    height: 58,
    resizeMode: "contain",
  },
  journeyTexts: {
    gap: 6,
  },
  journeyTitle: {
    fontSize: 16,
  },
  journeySubtitle: {
    fontSize: 12,
    color: colors.gray100,
  },
  journeyBadge: {
    position: "absolute",
    top: 18,
    right: 18,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#4dabff",
  },
  createJourneyCard: {
    width: 168,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  createJourneyIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.withe100,
  },
  createJourneyText: {
    fontSize: 16,
  },
  ctaCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 28,
    backgroundColor: "#0d1d8a",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  ctaTexts: {
    maxWidth: "65%",
    gap: 12,
  },
  ctaTitle: {
    fontSize: 18,
    color: colors.withe100,
  },
  ctaSubtitle: {
    fontSize: 12,
    color: "#E2E8FF",
  },
  ctaImage: {
    width: 78,
    height: 78,
    resizeMode: "contain",
  },
  bottomBarWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: colors.gray90,
    backgroundColor: colors.withe100,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  bottomAction: {
    minWidth: 62,
    height: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  bottomActionActive: {
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.yellow100,
  },
});
